spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_school
spring.datasource.username=yalcinumut
spring.datasource.password=199083
spring.datasource.driver-class-name=org.postgresql.Driver
